### ISSUE TITLE
IDE Layout Refactor

### ISSUE THREAD

**Issue by canmingir** [NucleoidJS/IDE#131]

**Comment by halilcengel** [comment]
> [!IMPORTANT]
We changed the **IDE Layout** in the project to **IDE Container**. Containers are a structure that also includes Page. The new Layouts were added to be used as they are mentioned in [Atomic Design](https://github.com/NucleoidJS/platform/wiki/How-we-use-atomic-design-in-NucleoidJS#how-we-use-atomic-design-in-nucleoidjs). 
 
> [!TIP]
> Added Layouts:
> - HorizontalSplitLayout
> - VerticalSplitLayout
> - BlankLayout

> We will explain Containers in more detail later on the Github Wiki.
